services:
  - type: web
    name: business-api
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: GCP_PROJECT_ID
        value: business-137ec
      - key: GCP_PRIVATE_KEY_ID
        value: 481f1908576db97037a118148858cc858fe4570c
      - key: GCP_PRIVATE_KEY
        value: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdJKbgSF0iyAp9\nv3452Yla9o/rNqIXXbQTiDfbhwp+kfCG5pu2ALyQDr7fem0ATpEWKn6RVi64eIEk\nq8B98v88m8mr0frE/h/yl9v1v73yIBsdtu84i/NMfK1A0XRtMmYtqSLyYc2y1cGw\nwQqA5rynaMwEDmGw0kOzi35EGJzkWAUaegOh/byIpZ7ZXk1pxhMfxK7q5eonFMWL\nC4BRYbgWT9+A3y8ecP6SnlVau/NkH1HdnYh2S6Eg8IqVC2LCUjN6S8VmJZbOE9MW\nFdAQUHNu+Eb4ZDFYOs1MYcsfJnUPxj2HTxoWSLDQ0A0RwXZAyeKeFq7ApHgJkOAg\nbVvQ/KwxAgMBAAECggEABELucJYdynfsyuiywlxbHHejwv/uCN6uZ7oxs5cXqoOI\nJ4xg7CBcfLadp/9Qremzhwubd5MD/NYtwGIU/AVnNQxPfYSZ/ZYbpS9HlIRA4SxM\nN/PSTHEFJc2awC997gkoGrRjwXl0A9XGpSWzBHhdZNfTcoe2T/5/vgJ6J9wYAxwy\nEqEaDTxXw4du4NC8eThR47lzkC18BChLhwbORbqbuDsc3HsyKicLe57eEk8W5lyj\nJzlTUVVZRQKPzDLoBKLV7L7ipL+bXkRQxpV0iqYVg4t+Isvqa4QNOhw89PC0YU+5\ni3i3jpjTnDS4pYSjap/dgJ8zWTYW0O3xuBPEAntQzQKBgQDPwiH2tgDjyIxkCLY1\n9bQngKbEHz2+OLjVkMcJ51xJtWKT2vDs3CHlZZAcL3cQXzZ8iOjzrUPiX+OZp2si\nwYwstl1FiKpRlMsWFKoXgGYTJ9S/J1GPU22Q01MlZ7k0D60ZJYv2oWYudQatokxP\nVexQg8qSrdO6+i0d7pSEVhwVlQKBgQDBocfWbNAoUQNidoqX37Mf3d7SLn/ZA5i7\nm5VV5DkBgWWO1KDZ0FdKDf/4rzmfEvLFJWPyf4tiqLtL7PwCkAuN5tp1HV1K7n/d\nUlbsugeqVVN4galqGqDWCP85n2ufj+jok2tXH2mE+43nhXSDZBvjDn4YxfEJQY0T\n0+7wlG8dLQKBgCtVzQvO7uSUYmRDRO6Ab7GFrkNeWNyirDsv1bSFI8TkJsm8c2CU\nkiVtR9/5LpalpZHYZO7fBzfi1HCqcThwsrJo34+vcAdQSAQ1Dz2TtLbuKfwtUV/a\nARKiYcd9mS34zxxdrpIlHFE4a8ov/kbWH1K0Cr8Jrw5jPKHvr97irzz5AoGAIvnU\nHRleqEmp8Nk0w6Y2tuTe4NxhX5PUvN6npPIqkekLrTcfLvkBK3FH8WXFZMSJca8F\nVMJRLSsJWfeetd/LFoDCqTD6rxRRqGq9JNmdlNkA0N2q+m2A6+iIIaJ4UEQwcAJg\n+0XDS7Acu9tRZoJovyTZBiSLG37putEncfF9+KkCgYEAtRHngN6chq2oa4YV+3tX\nhl9lJFqzgHNEXuIHFCzW/Qo2ZhM5B6QDwj+ETFCE7ujdo9DL1t91k1aHhj/9YfyB\n0W/0iAtFcgzAaHmWTEYrFP40RjwTCKQsU9ZvZPPv7o53hq4y3XHWL7NqoILZLCHx\nP7ixO6NptsH26lI9ISwpXRQ=\n-----END PRIVATE KEY-----\n
      - key: GCP_CLIENT_EMAIL
        value: firebase-adminsdk-jx5f1@business-137ec.iam.gserviceaccount.com
      - key: GCP_CLIENT_ID
        value: 112299600028808346377
      - key: GCP_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: GCP_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: GCP_AUTH_PROVIDER_X509_CERT_URL
        value: https://www.googleapis.com/oauth2/v1/certs
      - key: GCP_CLIENT_X509_CERT_URL
        value: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-jx5f1%40business-137ec.iam.gserviceaccount.com
